output_dir: "/n/scratch/users/s/sak0914/smk_output"
fastq_dir: "/n/data1/hms/dbmi/farhat/rollingDB/fastq_db"
isolates_to_run: "./test/isolates_to_run.tsv"
public_fastq: True
ref_genome: "/n/data1/hms/dbmi/farhat/mtb_data/h37rv/h37rv.fna"
kraken_db: "/n/data1/hms/dbmi/farhat/mtb_data/kraken/20220922_mtbDB"
scripts_dir: "./scripts"
references_dir: "./references"
min_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.90
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_gca_000195955"