output_dir: "/n/data1/hms/dbmi/farhat/rollingDB/TRUST/WGS" #"/n/scratch/users/s/sak0914/smk_output" #/n/data1/hms/dbmi/farhat/rollingDB/genomic_data"
fastq_dir: "/n/scratch/users/s/sak0914/TRUST_FASTQ" #"/n/data1/hms/dbmi/farhat/rollingDB/fastq_db"
isolates_to_run: "TRUST_isolates_to_run.tsv" #"./SRA_all/isolates_to_run.tsv"
kraken_db: "../kraken_db/custom_human_MTBC" #"/n/data1/hms/dbmi/farhat/mtb_data/kraken/20220922_mtbDB"
scripts_dir: "../scripts"
references_dir: "../references"
min_read_length: 50
median_depth: 15
min_cov: 1
genome_cov_prop: 0.50
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv" #"Mycobacterium_tuberculosis_gca_000195955"